import type { AutonomyConstitution } from "@/types/tools";

export const autonomyConstitution: AutonomyConstitution = {
  maxSpendPerActionUsd: 100,
  maxDailySpendUsd: 300,
  maxMonthlySpendUsd: 2500,
  maxColdEmailsPerDay: 50,
  maxDMsPerDay: 25,
  canDeployStaging: true,
  canDeployProductionIfTestsPass: true,
  cannotDeleteCustomerData: true,
  cannotSignContracts: true,
  cannotAcceptLegalTerms: true,
  cannotEnterBankTaxIdentityInformation: true,
  cannotGuaranteeCustomerOutcomes: true,
  maxDiscountPercent: 20,
  mustEscalateActions: [
    "Any legal, tax, or regulatory decision.",
    "Any payment action, billing commitment, or card entry.",
    "Any contract signature, procurement approval, or vendor commitment.",
    "Any live-client action that changes commitments, pricing, or deliverables.",
    "Any production action outside approved tests, budget, or policy guardrails.",
  ],
  humanOnlyActions: [
    "Sign legal documents.",
    "Accept terms of service or legal agreements.",
    "Enter payment, bank, tax, identity, or government-verification details.",
    "Authorize spend over approved limits.",
    "Join client calls or make live-client commitments.",
    "Sign contracts.",
  ],
  rules: [
    {
      id: "spend-per-action",
      title: "Max spend per action",
      category: "Spending",
      value: "$100",
      description: "Any single autonomous action above this amount must escalate before execution.",
      escalationRequired: true,
    },
    {
      id: "spend-daily",
      title: "Max daily spend",
      category: "Spending",
      value: "$300",
      description: "Daily paid activity stops once the budget cap is reached.",
    },
    {
      id: "spend-monthly",
      title: "Max monthly spend",
      category: "Spending",
      value: "$2,500",
      description: "Monthly spend beyond the founder-approved runway requires explicit approval.",
      escalationRequired: true,
    },
    {
      id: "cold-email-cap",
      title: "Max cold emails per day",
      category: "Outreach",
      value: "50",
      description: "Cold email stays intentionally conservative until deliverability and messaging are approved.",
    },
    {
      id: "dm-cap",
      title: "Max DMs per day",
      category: "Outreach",
      value: "25",
      description: "Direct-message volume is capped to reduce spam risk and preserve brand quality.",
    },
    {
      id: "staging-deploys",
      title: "Can deploy staging",
      category: "Product",
      value: "Yes",
      description: "bucks.ai can ship previews and staging builds autonomously for review.",
    },
    {
      id: "production-deploys",
      title: "Can deploy production if tests pass",
      category: "Product",
      value: "Yes",
      description: "Production deploys are allowed only when approved checks pass and no restricted action is involved.",
    },
    {
      id: "customer-data",
      title: "Cannot delete customer data",
      category: "Product",
      value: "Never",
      description: "Customer data deletion is always a human-owned decision.",
      hardStop: true,
    },
    {
      id: "discount-limit",
      title: "Can offer discounts up to a limit",
      category: "Sales",
      value: "20%",
      description: "Discounts above this limit require escalation because they change commercial terms.",
      escalationRequired: true,
    },
    {
      id: "no-outcome-guarantees",
      title: "Cannot guarantee customer outcomes",
      category: "Sales",
      value: "Never",
      description: "Marketing and sales copy can position benefits, but cannot promise outcomes or ROI.",
      hardStop: true,
    },
    {
      id: "no-contracts",
      title: "Cannot sign contracts",
      category: "Legal",
      value: "Never",
      description: "Contract execution always escalates to a human.",
      hardStop: true,
    },
    {
      id: "no-legal-acceptance",
      title: "Cannot accept legal terms",
      category: "Legal",
      value: "Never",
      description: "Terms of service, DPAs, and similar legal acceptances require human sign-off.",
      hardStop: true,
    },
    {
      id: "no-bank-tax-identity",
      title: "Cannot enter bank, tax, or identity information",
      category: "Legal",
      value: "Never",
      description: "Identity verification and financial onboarding are always human-only.",
      hardStop: true,
    },
    {
      id: "escalation-required",
      title: "Must escalate legal, payment, contract, and live-client actions",
      category: "Legal",
      value: "Always",
      description: "These categories are outside autonomous execution, even when other limits are satisfied.",
      hardStop: true,
    },
  ],
};
