import type { ToolRegistryItem } from "@/types/tools";

export const toolRegistry: ToolRegistryItem[] = [
  {
    id: "github",
    name: "GitHub",
    category: "Code",
    status: "Preferred",
    purpose: "Source control, pull requests, and autonomous code execution history.",
    typicalUse: "Create repos, open PRs, run CI, and manage issues for the MVP backlog.",
    riskLevel: "Medium",
    canAiSetupFully: false,
    requiresTermsAcceptance: false,
    requiresIdentityVerification: false,
    requiresPaymentSetup: false,
    defaultPermissions: ["Repository read/write", "Pull requests", "Actions metadata"],
    humanOnlyReasons: ["Org app installation and owner-level repository access approvals."],
    setupStatus: "Not Connected",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "Deployment",
    status: "Preferred",
    purpose: "Primary frontend hosting and preview deployment platform.",
    typicalUse: "Deploy the product site, preview environments, and production builds from Git.",
    riskLevel: "High",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: true,
    defaultPermissions: ["Project deploys", "Environment variable access", "Build logs"],
    humanOnlyReasons: ["Billing acceptance and production-domain ownership must be confirmed by a human."],
    setupStatus: "Awaiting Human Legal Step",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "Database",
    status: "Preferred",
    purpose: "Default Postgres, auth, and storage backend for founder products.",
    typicalUse: "Create a managed database, file storage, and secure app data layer for the MVP.",
    riskLevel: "High",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: true,
    defaultPermissions: ["Project provisioning", "Schema management", "Storage buckets"],
    humanOnlyReasons: ["Billing consent and data-region sign-off should be approved by a human."],
    setupStatus: "Awaiting Human Legal Step",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "Payments",
    status: "Preferred",
    purpose: "Payment processor for subscriptions, one-time purchases, and invoicing.",
    typicalUse: "Enable checkout, subscription management, coupons, and revenue tracking.",
    riskLevel: "Critical",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: true,
    requiresPaymentSetup: true,
    defaultPermissions: ["Products and prices", "Checkout sessions", "Webhook endpoints"],
    humanOnlyReasons: ["Legal acceptance, KYC, tax details, and bank account entry are human-only."],
    setupStatus: "Requires Identity Or Payment Step",
  },
  {
    id: "posthog",
    name: "PostHog",
    category: "Analytics",
    status: "Preferred",
    purpose: "Product analytics, funnels, feature flags, and session intelligence.",
    typicalUse: "Track activation, retention, experiments, and dashboard metrics from day one.",
    riskLevel: "Medium",
    canAiSetupFully: true,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: false,
    defaultPermissions: ["Project setup", "Event definitions", "Dashboard creation"],
    humanOnlyReasons: ["Initial workspace terms should still be accepted by an authorized human."],
    setupStatus: "Not Connected",
  },
  {
    id: "gmail-google-workspace",
    name: "Gmail / Google Workspace",
    category: "Outreach",
    status: "Preferred",
    purpose: "Operational email, outreach sending, and inbox-based customer workflows.",
    typicalUse: "Send founder-approved outbound, manage shared support mailboxes, and coordinate launch ops.",
    riskLevel: "High",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: true,
    defaultPermissions: ["Mailbox send access", "Draft creation", "Workspace admin scopes"],
    humanOnlyReasons: ["Workspace admin consent and outbound sending reputation policies need human review."],
    setupStatus: "Awaiting Human Legal Step",
  },
  {
    id: "airtable",
    name: "Airtable",
    category: "CRM",
    status: "Preferred",
    purpose: "Lightweight CRM, ops database, and campaign tracker.",
    typicalUse: "Manage leads, experiments, launch checklists, and founder-facing operating dashboards.",
    riskLevel: "Medium",
    canAiSetupFully: true,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: false,
    defaultPermissions: ["Base schema edits", "Views and automations", "Record read/write"],
    humanOnlyReasons: ["Workspace ownership and sharing rules should be approved by a human."],
    setupStatus: "Not Connected",
  },
  {
    id: "resend",
    name: "Resend",
    category: "Outreach",
    status: "Preferred",
    purpose: "Transactional and lifecycle email delivery.",
    typicalUse: "Power product emails, waitlist updates, and founder-approved onboarding sequences.",
    riskLevel: "Medium",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: true,
    defaultPermissions: ["Audience sync", "Domain records", "API send access"],
    humanOnlyReasons: ["Domain verification and sending-domain approval require human sign-off."],
    setupStatus: "Blocked By Verification",
  },
  {
    id: "openai",
    name: "OpenAI",
    category: "AI Model",
    status: "Preferred",
    purpose: "Primary LLM provider for planning, generation, and agent tasks.",
    typicalUse: "Generate blueprints, draft copy, classify feedback, and power internal agents.",
    riskLevel: "High",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: true,
    defaultPermissions: ["API key usage", "Model inference", "Usage dashboards"],
    humanOnlyReasons: ["Billing activation and policy acceptance must be completed by a human."],
    setupStatus: "Requires Identity Or Payment Step",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    category: "AI Model",
    status: "Preferred",
    purpose: "Secondary frontier model provider for reasoning and fallback capacity.",
    typicalUse: "Parallel reasoning tasks, policy-sensitive drafting, and model redundancy.",
    riskLevel: "High",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: true,
    defaultPermissions: ["API key usage", "Model inference", "Usage dashboards"],
    humanOnlyReasons: ["Billing and vendor approval require human ownership."],
    setupStatus: "Requires Identity Or Payment Step",
  },
  {
    id: "firecrawl",
    name: "Firecrawl",
    category: "Automation",
    status: "Preferred",
    purpose: "Web extraction and structured page crawling for research workflows.",
    typicalUse: "Research competitor sites, capture docs, and hydrate internal knowledge tasks.",
    riskLevel: "Medium",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: true,
    defaultPermissions: ["Crawl jobs", "Structured extraction", "API usage"],
    humanOnlyReasons: ["Usage-billing approval should be granted by a human."],
    setupStatus: "Requires Identity Or Payment Step",
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "Monitoring",
    status: "Preferred",
    purpose: "Error monitoring, tracing, and release health.",
    typicalUse: "Track production regressions, alert on crashes, and tie errors back to releases.",
    riskLevel: "Medium",
    canAiSetupFully: true,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: false,
    defaultPermissions: ["Project creation", "Release tracking", "Issue triage metadata"],
    humanOnlyReasons: ["Workspace terms and retention settings should be reviewed by a human."],
    setupStatus: "Not Connected",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "Domains",
    status: "Preferred",
    purpose: "DNS, edge security, and domain routing.",
    typicalUse: "Manage production domains, SSL, caching, and traffic protection.",
    riskLevel: "High",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: true,
    defaultPermissions: ["DNS records", "Workers config", "Zone settings"],
    humanOnlyReasons: ["Registrar ownership, billing, and DNS cutovers should be confirmed by a human."],
    setupStatus: "Blocked By Verification",
  },
  {
    id: "clerk",
    name: "Clerk",
    category: "Auth",
    status: "Preferred",
    purpose: "Managed auth, session handling, and user security workflows.",
    typicalUse: "Ship email, OAuth, and session management faster without a custom auth stack.",
    riskLevel: "High",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: false,
    defaultPermissions: ["Application setup", "Session config", "OAuth provider configuration"],
    humanOnlyReasons: ["Terms acceptance and external identity-provider approvals need a human."],
    setupStatus: "Awaiting Human Legal Step",
  },
  {
    id: "e2b-docker-sandbox",
    name: "E2B / Docker Sandbox",
    category: "Code",
    status: "Preferred",
    purpose: "Isolated execution sandboxes for code generation and verification tasks.",
    typicalUse: "Run builds, test generated code safely, and execute bounded automation steps.",
    riskLevel: "Low",
    canAiSetupFully: true,
    requiresTermsAcceptance: false,
    requiresIdentityVerification: false,
    requiresPaymentSetup: false,
    defaultPermissions: ["Ephemeral execution", "Package installs", "Filesystem sandboxing"],
    humanOnlyReasons: [],
    setupStatus: "Fully Completed",
  },
  {
    id: "railway",
    name: "Railway",
    category: "Deployment",
    status: "Approved",
    purpose: "Alternative deployment target for app services and background jobs.",
    typicalUse: "Host sidecars, queue workers, or databases when Vercel is not the best fit.",
    riskLevel: "Medium",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: true,
    defaultPermissions: ["Service deploys", "Environment variables", "Usage logs"],
    humanOnlyReasons: ["Billing approval is still required before production usage."],
    setupStatus: "Awaiting Human Legal Step",
  },
  {
    id: "render",
    name: "Render",
    category: "Deployment",
    status: "Approved",
    purpose: "Backup deployment platform for web services and background workers.",
    typicalUse: "Deploy APIs, cron jobs, and non-frontend workloads outside the primary stack.",
    riskLevel: "Medium",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: true,
    defaultPermissions: ["Service deploys", "Environment variables", "Build logs"],
    humanOnlyReasons: ["Billing activation and domain delegation need human approval."],
    setupStatus: "Awaiting Human Legal Step",
  },
  {
    id: "firebase",
    name: "Firebase",
    category: "Database",
    status: "Approved",
    purpose: "Alternative Google-backed backend for realtime data and mobile-first products.",
    typicalUse: "Ship realtime prototypes, notifications, and mobile-friendly auth or storage flows.",
    riskLevel: "High",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: true,
    defaultPermissions: ["Project creation", "Firestore rules", "Hosting config"],
    humanOnlyReasons: ["Google billing and organization ownership must be approved by a human."],
    setupStatus: "Requires Identity Or Payment Step",
  },
  {
    id: "neon",
    name: "Neon",
    category: "Database",
    status: "Approved",
    purpose: "Serverless Postgres option for branching and preview environments.",
    typicalUse: "Create isolated preview databases and lightweight Postgres environments quickly.",
    riskLevel: "Medium",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: false,
    defaultPermissions: ["Database branches", "Connection strings", "Schema migrations"],
    humanOnlyReasons: ["Workspace ownership and commercial terms need human confirmation."],
    setupStatus: "Not Connected",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    category: "CRM",
    status: "Approved",
    purpose: "Full CRM and lifecycle marketing platform for more mature go-to-market operations.",
    typicalUse: "Track deals, lifecycle stages, website forms, and customer touchpoints in one place.",
    riskLevel: "High",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: true,
    defaultPermissions: ["Contacts", "Deals", "Email templates"],
    humanOnlyReasons: ["Account ownership, billing, and contact-governance policies require human review."],
    setupStatus: "Awaiting Human Legal Step",
  },
  {
    id: "linear",
    name: "Linear",
    category: "Automation",
    status: "Approved",
    purpose: "Execution tracker for product, bugs, and agent-created work queues.",
    typicalUse: "Plan releases, sync backlog items, and keep autonomous work visible to the founder.",
    riskLevel: "Low",
    canAiSetupFully: true,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: false,
    defaultPermissions: ["Issue creation", "Cycle tracking", "Project metadata"],
    humanOnlyReasons: ["Workspace-level invite policies should be confirmed by a human."],
    setupStatus: "Not Connected",
  },
  {
    id: "slack",
    name: "Slack",
    category: "Automation",
    status: "Approved",
    purpose: "Internal notifications, approvals, and async ops communication.",
    typicalUse: "Post deploy alerts, route approval requests, and keep the founder looped in.",
    riskLevel: "Medium",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: false,
    defaultPermissions: ["Channel posting", "Bot scopes", "Approval messages"],
    humanOnlyReasons: ["Workspace admin consent is required before broad posting access is granted."],
    setupStatus: "Awaiting Human Legal Step",
  },
  {
    id: "discord",
    name: "Discord",
    category: "Outreach",
    status: "Approved",
    purpose: "Community support and founder-led customer engagement.",
    typicalUse: "Run waitlist communities, collect feedback, and host early adopter groups.",
    riskLevel: "Medium",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: false,
    defaultPermissions: ["Bot posting", "Channel moderation", "Community notifications"],
    humanOnlyReasons: ["Server ownership and moderation policies should stay with a human owner."],
    setupStatus: "Not Connected",
  },
  {
    id: "apollo",
    name: "Apollo",
    category: "Outreach",
    status: "Blocked",
    purpose: "Prospect database and outbound contact enrichment.",
    typicalUse: "Source lead lists and enrich contacts for sales sequences when explicitly approved.",
    riskLevel: "Critical",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: true,
    defaultPermissions: ["List export", "Contact enrichment", "Sequence enrollment"],
    humanOnlyReasons: ["Contact acquisition and compliance risk make this blocked by default."],
    setupStatus: "Rejected By Policy",
  },
  {
    id: "clay",
    name: "Clay",
    category: "Marketing",
    status: "External Approval Required",
    purpose: "Advanced enrichment and personalized growth workflows.",
    typicalUse: "Build tailored lead research pipelines and enrich records before approved outreach.",
    riskLevel: "High",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: false,
    requiresPaymentSetup: true,
    defaultPermissions: ["Enrichment tables", "Workflow runs", "CRM sync"],
    humanOnlyReasons: ["External data-usage approval is required before enrichment workflows can run."],
    setupStatus: "Awaiting Human Legal Step",
  },
  {
    id: "smartlead",
    name: "Smartlead",
    category: "Outreach",
    status: "External Approval Required",
    purpose: "Cold email infrastructure and inbox rotation.",
    typicalUse: "Scale outbound experiments after the founder approves list quality and messaging guardrails.",
    riskLevel: "Critical",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: true,
    requiresPaymentSetup: true,
    defaultPermissions: ["Campaign setup", "Mailbox rotation", "Sequence performance"],
    humanOnlyReasons: ["Deliverability ownership, mailbox verification, and compliance sign-off are required."],
    setupStatus: "Blocked By Verification",
  },
  {
    id: "instantly",
    name: "Instantly",
    category: "Outreach",
    status: "External Approval Required",
    purpose: "Cold email sending and campaign optimization.",
    typicalUse: "Operate founder-approved outbound tests with carefully bounded sending limits.",
    riskLevel: "Critical",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: true,
    requiresPaymentSetup: true,
    defaultPermissions: ["Campaign setup", "Mailbox warmup", "Analytics dashboards"],
    humanOnlyReasons: ["Domain reputation and compliance review must be completed by a human."],
    setupStatus: "Blocked By Verification",
  },
  {
    id: "google-ads",
    name: "Google Ads",
    category: "Ads",
    status: "Human Only",
    purpose: "Search and performance advertising for high-intent acquisition.",
    typicalUse: "Run tightly capped acquisition experiments once a human approves creatives, targeting, and spend.",
    riskLevel: "Critical",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: true,
    requiresPaymentSetup: true,
    defaultPermissions: ["Campaign drafts", "Conversion tracking", "Budget recommendations"],
    humanOnlyReasons: ["Ad account billing, policy liability, and live spend control remain human-only."],
    setupStatus: "Requires Identity Or Payment Step",
  },
  {
    id: "meta-ads",
    name: "Meta Ads",
    category: "Ads",
    status: "Human Only",
    purpose: "Paid social acquisition across Facebook and Instagram.",
    typicalUse: "Launch audience tests and retargeting only after human creative and billing approval.",
    riskLevel: "Critical",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: true,
    requiresPaymentSetup: true,
    defaultPermissions: ["Campaign drafts", "Pixel mapping", "Audience recommendations"],
    humanOnlyReasons: ["Business verification, payments, and ad-policy risk are human-only responsibilities."],
    setupStatus: "Requires Identity Or Payment Step",
  },
  {
    id: "tiktok-ads",
    name: "TikTok Ads",
    category: "Ads",
    status: "Human Only",
    purpose: "Paid social reach for creator-led or consumer acquisition experiments.",
    typicalUse: "Test short-form paid distribution after a human approves brand safety and budget limits.",
    riskLevel: "Critical",
    canAiSetupFully: false,
    requiresTermsAcceptance: true,
    requiresIdentityVerification: true,
    requiresPaymentSetup: true,
    defaultPermissions: ["Campaign drafts", "Pixel mapping", "Spend pacing insights"],
    humanOnlyReasons: ["Billing, business verification, and live ad approvals stay with a human owner."],
    setupStatus: "Requires Identity Or Payment Step",
  },
];

export const preferredTools = toolRegistry.slice(0, 15);
export const extendedTools = toolRegistry.slice(15);
