// Server-side GitHub REST API client.
// All functions require GITHUB_PERSONAL_ACCESS_TOKEN in the environment.
// Never import from client components.

import { getGitHubEnv } from "@/lib/github/env";
import type {
  CreateGitHubRepoInput,
  GitHubRepoRecord,
  CreateGitHubRepoResult,
  GitHubFileTemplate,
} from "@/types/github";

const GITHUB_API_BASE = "https://api.github.com";
const GITHUB_API_VERSION = "2022-11-28";

function githubHeaders(token: string): HeadersInit {
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": GITHUB_API_VERSION,
    "Content-Type": "application/json",
  };
}

export interface GitHubAuthenticatedUser {
  login: string;
  id: number;
  name: string | null;
  email: string | null;
}

export async function getAuthenticatedGitHubUser(): Promise<GitHubAuthenticatedUser> {
  const { token } = getGitHubEnv();

  const res = await fetch(`${GITHUB_API_BASE}/user`, {
    headers: githubHeaders(token),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`GitHub /user failed (${res.status}): ${body}`);
  }

  const data = (await res.json()) as GitHubAuthenticatedUser;
  return data;
}

export async function createGitHubRepository(
  input: CreateGitHubRepoInput
): Promise<CreateGitHubRepoResult> {
  const { token } = getGitHubEnv();

  const body = {
    name: input.name,
    description: input.description ?? "",
    private: input.visibility === "private",
    auto_init: false,
  };

  const res = await fetch(`${GITHUB_API_BASE}/user/repos`, {
    method: "POST",
    headers: githubHeaders(token),
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const errBody = await res.text();
    throw new Error(`GitHub repo creation failed (${res.status}): ${errBody}`);
  }

  const repo = (await res.json()) as GitHubRepoRecord;

  return {
    repoUrl: repo.html_url,
    fullName: repo.full_name,
    owner: repo.owner.login,
    name: repo.name,
    repoId: repo.id,
    cloneUrl: repo.clone_url,
    sshUrl: repo.ssh_url,
    private: repo.private,
  };
}

export async function createOrUpdateGitHubFile(input: {
  owner: string;
  repo: string;
  file: GitHubFileTemplate;
}): Promise<void> {
  const { token } = getGitHubEnv();
  const { owner, repo, file } = input;

  const encoded = Buffer.from(file.content, "utf-8").toString("base64");

  const res = await fetch(
    `${GITHUB_API_BASE}/repos/${owner}/${repo}/contents/${file.path}`,
    {
      method: "PUT",
      headers: githubHeaders(token),
      body: JSON.stringify({
        message: file.message,
        content: encoded,
      }),
    }
  );

  if (!res.ok) {
    const errBody = await res.text();
    throw new Error(
      `GitHub file write failed for ${file.path} (${res.status}): ${errBody}`
    );
  }
}

export async function createStarterRepositoryFiles(input: {
  owner: string;
  repo: string;
  businessName: string;
  oneLineIdea?: string | null;
}): Promise<void> {
  const { owner, repo, businessName, oneLineIdea } = input;

  const safeName = businessName.trim() || repo;
  const ideaLine = oneLineIdea
    ? `\n> ${oneLineIdea.trim()}\n`
    : "";

  const files: GitHubFileTemplate[] = [
    {
      path: "README.md",
      message: "chore: add starter README",
      content: `# ${safeName}
${ideaLine}
_Generated by [bucks.ai](https://bucks.ai)_

> **Initial scaffold only — no production code generated yet.**

This repository was created automatically as part of the bucks.ai startup operator flow.
A founder or agent will fill in real code once execution begins.
`,
    },
    {
      path: ".gitignore",
      message: "chore: add .gitignore",
      content: `# Dependencies
node_modules/
.pnp
.pnp.js

# Build output
.next/
out/
dist/
build/

# Environment
.env
.env.local
.env.*.local

# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Editor
.DS_Store
.vscode/
.idea/
`,
    },
    {
      path: "package.json",
      message: "chore: add placeholder package.json",
      content: JSON.stringify(
        {
          name: repo,
          version: "0.1.0",
          private: true,
          scripts: {
            dev: "echo 'Starter repo created by bucks.ai'",
          },
        },
        null,
        2
      ) + "\n",
    },
    {
      path: "src/README.md",
      message: "chore: add src placeholder",
      content: `# Source

Source code will be generated here by the bucks.ai agent once execution begins.

_Initial scaffold only — no production code generated yet._
`,
    },
  ];

  // Write files serially — GitHub's API can reject parallel writes on a brand-new repo
  for (const file of files) {
    await createOrUpdateGitHubFile({ owner, repo, file });
  }
}
